name: Bug Report
description: Bir hatayı bildir
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Açıklama
      placeholder: Hata nedir?

  - type: textarea
    attributes:
      label: Beklenen davranış

  - type: textarea
    attributes:
      label: Ekran görüntüsü